# Generated by Django 4.1 on 2022-12-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='destination',
            new_name='flight_destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin',
            new_name='flight_origin',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='status',
        ),
    ]
