# Generated by Django 4.1 on 2022-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_destination_flight_flight_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_arrival',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_return',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
