# Generated by Django 4.1 on 2022-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_flight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_gate',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
