# Generated by Django 4.1 on 2022-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_flight_flight_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_seat',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
